config/routes.rb
Rails.application.routes.draw do
  get 'settings/edit', to: 'settings#edit', as: :settings_edit
  get 'fetch_weather', to: 'routines#fetch_weather'
  patch 'computer_times/update_one_min', to: "computer_times#update_one_min"
  patch 'routines/complete_morning_routine', to: 'routines#complete_morning_routine', as: :complete_morning_routine
  patch 'routines/complete_night_routine', to: 'routines#complete_night_routine', as: :complete_night_routine
  patch 'settings/update-city', to: 'settings#update_city'
  patch 'settings/toggle_morning_notification', to: 'settings#toggle_morning_notification', as: :morning_toggle
  patch 'settings/toggle_night_notification', to: 'settings#toggle_night_notification', as: :night_toggle
  patch 'settings/update_night_time', to: 'settings#update_night_time', as: :update_night
  patch 'settings/update_morning_time', to: 'settings#update_morning_time', as: :update_morning
  patch 'settings/toggle_eye_break_notification', to: 'settings#toggle_eye_break_notification', as: :toggle_eye_break
  get 'resources', to: 'resources#index', as: :resources
  get 'blinking-exercises', to: 'exercises#index', as: :exercises
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_dashboard_icon.html.erb
<svg width="45" height="32" viewBox="0 0 45 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M43.7369 2.66285C43.734 2.66285 43.7311 2.66285 43.7283 2.66285H40.7975V1.65998C40.8133 1.26305 40.5565 0.906325 40.175 0.795448C38.1403 0.262245 36.0451 -0.00511317 33.9417 7.40501e-05C30.4836 7.40501e-05 25.7718 0.778157 22.2878 4.32276C18.8296 0.743576 14.0833 7.40501e-05 10.6338 7.40501e-05C8.53038 -0.00511317 6.43518 0.262245 4.40049 0.795448C4.01901 0.906325 3.76225 1.26305 3.77802 1.65998V2.6542H0.864537C0.387096 2.6542 0 3.0413 0 3.51874V31.132C0 31.6095 0.387096 31.9966 0.864537 31.9966C1.01302 31.9961 1.15891 31.9574 1.28816 31.8842C1.37461 31.841 10.02 27.1119 22.0889 30.1551H22.2186H22.2964C22.3653 30.1634 22.4349 30.1634 22.5039 30.1551C34.6074 27.086 43.2528 31.8064 43.3046 31.8842C43.5721 32.0386 43.9017 32.0386 44.1692 31.8842C44.435 31.7307 44.5996 31.4477 44.6014 31.1407V3.52738C44.6014 3.04994 44.2145 2.66285 43.7369 2.66285ZM1.72907 29.7574V4.39192H3.79532V26.0745C3.78991 26.5519 4.17258 26.9434 4.65002 26.9488C4.6967 26.9493 4.74339 26.9461 4.78953 26.939C6.57804 26.6659 8.38373 26.5215 10.1929 26.5068C12.699 26.4633 15.1946 26.8403 17.576 27.622C12.1981 26.9717 6.74306 27.7067 1.72907 29.7574ZM10.1929 24.7863C8.6204 24.7899 7.04975 24.8909 5.48981 25.0889V2.34297C7.17306 1.96798 8.89197 1.77659 10.6165 1.77237C13.8499 1.77237 18.3109 2.51588 21.4059 6.0086L21.4319 27.5442C19.6336 26.3684 16.1236 24.7863 10.1929 24.7863ZM23.1609 6.0086C26.256 2.55046 30.717 1.77237 33.9503 1.77237C35.6748 1.77745 37.3937 1.96873 39.0771 2.34297V25.0889C37.5259 24.8891 35.9639 24.7851 34.3999 24.7777C28.5038 24.7777 24.9851 26.3598 23.1609 27.5356V6.0086ZM42.8637 29.7574C37.839 27.7011 32.3715 26.9659 26.9822 27.622C29.3749 26.8374 31.8824 26.4604 34.3999 26.5068C36.2204 26.5169 38.0378 26.6585 39.8378 26.9304C40.3099 27.002 40.7507 26.6774 40.8223 26.2054C40.8294 26.1592 40.8326 26.1125 40.8321 26.0658V4.39192H42.8983L42.8637 29.7574Z" fill="#02196C"/>
</svg>

app/views/shared/_desktopnavbar.html.erb
<div class="navbar-links">
  <%= link_to 'Dashboard', dashboard_path %>
  <%= link_to 'Blinking Exercises', exercises_path %>
  <%= link_to 'Resources', resources_path %>
  <%= link_to 'Settings', settings_edit_path %>
</div>

app/views/shared/_desktoptabs.html.erb
<div class="navbar-links">
  <%= link_to 'Dashboard', dashboard_path %>
  <%= link_to 'Blinking Exercises', exercises_path %>
  <%= link_to 'Resources', resources_path %>
  <%= link_to 'Settings', settings_edit_path %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex align-items-center">
  <div class="footer-links flex-grow-1">
    <a href="/dashboard" class="footer-link <%= 'active' if @tab == 'dashboard' %>">
      <%= render 'shared/dashboard_icon' %>
    </a>
    <a href="/blinking-exercises" class="footer-link <%= 'active' if @tab == 'exercises' %>">
      <%= render 'shared/exercise_icon' %>
    </a>
     <a href="/resources" class="footer-link <%= 'active' if @tab == 'resources' %>">
      <%= render 'shared/resources_icon' %>
    </a>
     <a href="/settings/edit" class="footer-link <%= 'active' if @tab == 'settings' %>">
      <%= render 'shared/settings_icon' %>
    </a>
  </div>
</div>

app/views/shared/_mobilenavbar.html.erb
<div class="navbar-links">
  <%= link_to 'Dashboard', dashboard_path %>
  <%= link_to 'Blinking Exercises', exercises_path %>
  <%= link_to 'Resources', resources_path %>
  <%= link_to 'Settings', settings_edit_path %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler clickable" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_resources_icon.html.erb
<svg width="38" height="38" viewBox="0 0 38 38" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M20.5832 9.5C20.5832 10.3744 19.8744 11.0832 19 11.0832C18.1256 11.0832 17.4168 10.3744 17.4168 9.5C17.4168 8.62561 18.1256 7.91676 19 7.91676C19.8744 7.91676 20.5832 8.62561 20.5832 9.5Z" fill="#02196C"/>
<path d="M19 30.0832C18.3445 30.0832 17.8125 29.5512 17.8125 28.8957V16.625H16.2293C15.5738 16.625 15.0418 16.093 15.0418 15.4375C15.0418 14.782 15.5738 14.25 16.2293 14.25H19C19.6555 14.25 20.1875 14.782 20.1875 15.4375V28.8957C20.1875 29.5512 19.6555 30.0832 19 30.0832Z" fill="#02196C"/>
<path d="M19 38C8.52298 38 0 29.477 0 19C0 8.52298 8.52298 0 19 0C29.477 0 38 8.52298 38 19C38 29.477 29.477 38 19 38ZM19 2.375C9.83253 2.375 2.375 9.83253 2.375 19C2.375 28.1675 9.83253 35.625 19 35.625C28.1675 35.625 35.625 28.1675 35.625 19C35.625 9.83253 28.1675 2.375 19 2.375Z" fill="#02196C"/>
<path d="M22.5625 30.0832H15.4375C14.782 30.0832 14.25 29.5512 14.25 28.8957C14.25 28.2402 14.782 27.7082 15.4375 27.7082H22.5625C23.218 27.7082 23.75 28.2402 23.75 28.8957C23.75 29.5512 23.218 30.0832 22.5625 30.0832Z" fill="#02196C"/>
</svg>