config/routes.rb
Rails.application.routes.draw do
  get 'settings/edit', to: 'settings#edit', as: :settings_edit
  get 'fetch_weather', to: 'routines#fetch_weather'
  patch 'computer_times/update_one_min', to: "computer_times#update_one_min"
  patch 'routines/complete_morning_routine', to: 'routines#complete_morning_routine', as: :complete_morning_routine
  patch 'routines/complete_night_routine', to: 'routines#complete_night_routine', as: :complete_night_routine
  patch 'settings/update-city', to: 'settings#update_city'
  patch 'settings/toggle_morning_notification', to: 'settings#toggle_morning_notification', as: :morning_toggle
  patch 'settings/toggle_night_notification', to: 'settings#toggle_night_notification', as: :night_toggle
  patch 'settings/update_night_time', to: 'settings#update_night_time', as: :update_night
  patch 'settings/update_morning_time', to: 'settings#update_morning_time', as: :update_morning
  patch 'settings/toggle_eye_break_notification', to: 'settings#toggle_eye_break_notification', as: :toggle_eye_break
  get 'resources', to: 'resources#index', as: :resources
  get 'blinking-exercises', to: 'exercises#index', as: :exercises
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_desktop_login.html.erb
<div class="background" style="background-image: url(<%= image_url('backgrounds/desktopback.svg') %>)">

  <div class="desktop_header_links">

    <div class="title-underlined mr-4">
      <%= link_to "SIGN UP", new_user_registration_path, class: "title" %>
    </div>

  </div>

  <div class="blink_header_desktop">
    <h1> <%= link_to root_path, class: "no-decoration" do %> BLINK <% end %><%= image_tag("logo-blink.svg", height:"33.6", width:"102.19", alt:"vector") %></h1>
  </div>

  <div class="motto_desktop">
    <h2>Show your eyes <br> some love</h2>
  </div>

  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="form-inputs container" id="loginFormDesktop">
      <%= f.input :email,
                  label: false,
                  required: false,
                  input_html: { autocomplete: "email", placeholder: 'EMAIL' } %>
      <%= f.input :password,
                  required: false,
                  label: false,
                  input_html: { autocomplete: "current-password", placeholder: 'PASSWORD' } %>
                  <br><br>
      <div id="remember-me">
          <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
      </div>
    </div>
  <div class="text-center">
    <div class="form-actions desk-button button btn btn-outline-success mb-5 text-center">
      <%= f.button :submit, "LOG IN", class: "orange-text" %>
    </div>
  </div>
  <% end %>

</div>

app/views/pages/_mobile_login.html.erb
<div class="background background-mobile" style="background-image: url(<%= image_url 'backgrounds/mobile-form-background.svg' %>)">

  <div class="container">

    <div class="banner-mobile">
      <%= link_to root_path, class: "blink-header no-decoration" do %>
          <h1 class="blink-name mb-0 no-decoration">BLINK</h1>
          <%= image_tag (image_url('logo-blink.svg')), class:"blink-logo no-decoration" %>
      <% end %>
    </div>

    <div class="mobile-sign-out">
      <div class="title-underlined">
        <%= link_to "SIGN UP", new_user_registration_path, class: "title" %>
      </div>
    </div>

  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="form-inputs container loginFormMobile" id="loginForm">

      <%= f.input :email,
                  label: false,
                  required: false,
                  autofocus: true,
                  input_html: { autocomplete: "email", placeholder: 'EMAIL' } %>
      <%= f.input :password,
                  label: false,
                  required: false,
                  input_html: { autocomplete: "current-password", placeholder: 'PASSWORD' } %>
                  <br><br>
      <div style="margin: 0 21%">
        <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
      </div>
    </div>
  <div class="text-center">
    <div class="form-actions desk-button button btn btn-outline-success mb-3 text-center">
      <%= f.button :submit, "Log in" %>
    </div>
  </div>
  <% end %>


  </div>
</div>

app/views/pages/desktop_dashboard.html.erb
<div class="background" style="background-image: url(<%= image_url 'backgrounds/desktopback.svg' %>)">

  <div class="desktop_header_links">

    <div class="title-underlined mr-4">
      <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete, class:"title" %>
    </div>

  </div>

  <div class="blink_header_desktop">
    <h1>BLINK <%= image_tag("logo-blink.svg", height:"33.6", width:"102.19", alt:"vector") %></h1>
  </div>


  <div class="container-blink-desktop">


    <div class="d-flex justify-content-end">

      <div class="custom-control custom-switch card-blink toggle-button-container text-center eye-break">
        <p class="notification-title">EYE BREAK NOTIFICATION</p>
        <div class="toggle-div">
          <input type="checkbox" class="custom-control-input" id="switch-eye-break" <%= 'checked' if current_user.setting.eye_break_notification_active %>>
          <label class="custom-control-label" for="switch-eye-break"></label>
          <div hidden id='eye-break-notification-active'><%= current_user.setting.eye_break_notification_active %></div>
        </div>
      </div>

    </div>





    <!-- Tab links -->
    <div class="tabs-blink">
      <div class="tab-blink <%= 'active' if @tab == 'dashboard' %> clickable" onclick="window.openTabs(event, 'Dashboard')"><h3>DASHBOARD</h3></div>
      <div class="tab-blink <%= 'active' if @tab == 'exercises' %> clickable" onclick="window.openTabs(event, 'Blinking Exercises')"><h3>BLINKING EXERCISES</h3></div>
      <div class="tab-blink <%= 'active' if @tab == 'resources' %> clickable" onclick="window.openTabs(event, 'Resources')"><h3>RESOURCES</h3></div>
      <div class="tab-blink <%= 'active' if @tab == 'settings' %> clickable" onclick="window.openTabs(event, 'Settings')"><h3>SETTINGS</h3></div>
    </div>

    <!-- Tab content -->
    <div id="Dashboard" class="tabcontent tabcontent-blink <%= 'active' if @tab == 'dashboard' %>">

      <div id="dashboard">

        <div class="board-part board-part-desktop">

          <div id="board" class="desktop" data-city="<%= current_user.city %>">

            <div class="board-top">

              <div class="board-section top-left">
                <div class="board-content temperature">
                  <div id="weather-temperature"></div>
                  <div id="weather-degrees">°C</div>
                </div>
                <div class="board-label">
                  TEMPERATURE
                </div>
              </div>

              <div class="board-section top-right">
                <div class="board-content">
                  <img id="weather-icon">
                </div>
                <div class="board-label">
                  <div id="weather-description"></div>
                </div>
              </div>

            </div>


            <div class="board-bottom">

              <div class="board-section bottom-left">
                <div class="board-content">
                  <%= image_tag (image_url('vectors/computer.svg')), id:"computer-icon" %>
                  <div class="computer-time">
                    <% if @computer_time %>
                      <div id="computer-time" data-computer-time-minutes="<%= @computer_time.minutes %>">

                        <% nb_hrs = (@computer_time.minutes / 60).floor %>
                        <% nb_min = @computer_time.minutes % 60 %>
                        <p>
                          <span id="computer-time-hrs"><%= "#{nb_hrs}h" unless (nb_hrs.zero? && !nb_min.zero?) %></span><span id="computer-time-min"><%= "0" if (nb_min<10 && !nb_hrs.zero?) %><%= nb_min unless (nb_hrs.zero? && nb_min.zero?)%><%= "min" if (nb_hrs.zero? && !nb_min.zero?) %></span>
                        </p>

                      </div>

                    <% else %>
                      <div id="computer-time" data-computer-time-minutes="<%= 0 %>">
                        <p>
                          <span id="computer-time-hrs">0h</span><span id="computer-time-min"></span>
                        </p>
                      </div>
                    <% end %>

                  </div>
                </div>
                <div class="board-label">
                  COMPUTER TIME
                </div>
              </div>

              <div class="board-section humidity bottom-right">
                <div class="board-content humidity">
                  <div id="weather-humidity"></div>
                  <%= image_tag (image_url('vectors/humidity.svg')) %>
                </div>
                <div class="board-label">
                  HUMIDITY
                </div>
              </div>

            </div>

          </div>

        </div>


        <div class="routines desktop">

          <% if @routine_morning %>

            <div class="routine">
                <div id="completed-morning">
                  <%= image_tag (image_url("vectors/completed#{"_not" unless @routine_morning.completed}.svg")) %>
                </div>

                <div class="card-blink desktop card-routine desktop morning">
                  <div class="routine-header">
                    <h2> MORNING ROUTINE</h2>
                    <div class="play-btn-page-div">
                      <% exercise_asset_path = "sounds/#{@routine_morning.exercise.title.downcase.split().join('-')}-#{@routine_morning.repetition}.wav" %>
                      <div class="page__play-btn play-btn-routine morning" data-sound="<%= image_url(exercise_asset_path) %>">
                        <i class='fas fa-play-circle'></i>
                      </div>
                    </div>
                  </div>
                    <div class="routine-infos">
                      <p><%= @routine_morning.exercise.title %></p>
                      <p><%= @routine_morning.repetition %> reps</p>
                    </div>
                </div>


            </div>
          <% end %>


          <% if @routine_night %>

            <div class="routine">
                <div id="completed-night">
                  <%= image_tag (image_url("vectors/completed#{"_not" unless @routine_night.completed}.svg")) %>
                </div>


                <div class="card-blink desktop card-routine night"
                        data-title='<%= @routine_night.exercise.title %>' data-directions='<%= @routine_night.exercise.directions %>' data-repetition='<%= @routine_night.repetition %>'
                        data-sound="<%= image_url(exercise_asset_path) %>">
                    <div class="routine-header">
                      <h2> NIGHT ROUTINE </h2>
                      <div class="play-btn-page-div">
                        <% exercise_asset_path = "sounds/#{@routine_night.exercise.title.downcase.split().join('-')}-#{@routine_night.repetition}.wav" %>
                        <div class="page__play-btn play-btn-routine night" data-sound="<%= image_url(exercise_asset_path) %>">
                          <i class='fas fa-play-circle'></i>
                        </div>
                      </div>
                    </div>
                    <div class="routine-infos">
                      <p><%= @routine_night.exercise.title %></p>
                      <p><%= @routine_night.repetition %> reps</p>
                    </div>
                </div>


            </div>
          <% end %>

        </div>

      </div>

    </div>

    <div id="Blinking Exercises" class="tabcontent tabcontent-blink <%= 'active' if @tab == 'exercises' %>">

      <div class="desktop-grid-1-1">

        <% @exercises.each do |exercise| %>

          <div class="card-blink">

            <div class="card-blink-content exercise">


              <div class="card-blink-play-part">
                <div class="play-btn-page-div" id='<%= exercise.id %>'>
                  <% exercise_asset_path = "sounds/#{exercise.title.downcase.split().join('-')}-1.wav" %>
                  <div class="page__play-btn" data-sound="<%= asset_url(exercise_asset_path) %>">
                    <i class='fas fa-play-circle'></i>
                  </div>
                </div>
              </div>

              <div class="card-blink-infos exercise">
                <h2><%= exercise.title %></h2>
                <p><%= exercise.summary %></p>
              </div>

            </div>

          </div>

        <% end %>

      </div>


    </div>

    <div id="Resources" class="tabcontent tabcontent-blink <%= 'active' if @tab == 'resources' %>">

      <div class="desktop-grid-1-1">

        <div class="clickable" data-toggle="collapse" data-target="#collapseWhyBlink" aria-expanded="false" aria-controls="collapseWhyBlink">
          <div class="card-blink desktop-resource">
            <h2>WHY BLINK?</h2>
            <p class="summary"> Learn why our devices can cause dry eyes.</p>
            <div class="collapse" id="collapseWhyBlink" style="border-top: 0.5px solid $soft-orange; text-align: justify; margin-top: 25px; padding-top: 25px;">
              <p>As phone and computer screens become more ubiquitious, it’s important to educate ourselves on the dangers that using these devices present to our eye health.</p>
              <p>Before computer and phone screens became a part of our daily lives, people blinked 12 - 18 times per minute. Because of these devices, people now blink about 5 times per minute.</p>
              <p>Not blinking often enough can lead to a dry eye disease called Meibomian Gland Dysfunction, or MGD, and here’s why: everyone has tiny glands in their top and bottom eyelids called meibomian glands. These glands produce an oily substance called meibum that prevents evaporation of the eye’s tear film. The only way that meibum is secreted into your eyes is through blinking.</p>
              <p>Due to a combination of not blinking enough and using smart devices at younger ages, children as young as seven are being diagnosed with MGD. Until recently, this was most often diagnosed in people 50 years or older.</p>
              <p>We're not helpless against these symptoms, however. Use this app to build better habits and eye health.</p>
            </div>
          </div>
        </div>

        <div class="clickable" data-toggle="collapse" data-target="#collapseHygiene" aria-expanded="false" aria-controls="collapseHygiene">
          <div class="card-blink desktop-resource">
            <h2>TIPS FOR GREAT EYE HYGIENE!</h2>
            <p class="summary"> Learn how to take care of your eyes and reduce dry eye symptoms.</p>
            <div class="collapse" id="collapseHygiene" style="border-top: 0.5px solid $soft-orange; text-align: justify; margin-top: 25px; padding-top: 25px;">
              <p>You might wonder why cleaning your eye lids everyday is so important. As trivial as it may seem, cleaning your eye lids on a daily basis is one of the best hygiene habits you can practice!</p>
              <p>Other than blinking, cleaning your eye lids is a great way to prevent those red, itchy eyes. For the vast majority of people with dry eyes, the problem starts with the oil glands in our eyelids called the Meibomian Glands. If you don’t clean your eyelids regularly, debris can build up over time and clog these glands. This leads to unstable tear film, which can cause Meibomian Gland Dysfunction, or MGD.</p>
              <p>We recommend cleaning your eyelids twice per day. Ask your doctor what to use for the cleaning agent (options usually include warm water, diluted baby shampoo, or over-the-counter or prescription eyelid cleanser), and simply follow these steps for clean eyelids: </p>
              <ul>
                <li>Wash your hands, and then moisten a clean washcloth, cotton swab, or gauze pad with the cleaning solution.</li>
                <li>Gently wipe your eyelashes and lids.</li>
                <li>Rinse with warm water.</li>
                <li>Repeat the process for your other eye using a different washcloth, swab or pad.</li>
              </ul>
              <p>And you’re done! You’re on the path to healthier eyes already!</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="Settings" class="tabcontent tabcontent-blink <%= 'active' if @tab == 'settings' %>">

      <div class="desktop-settings">

        <div class="custom-control custom-switch card-blink toggle-button-container text-center">
          <p class="notification-title">MORNING NOTIFICATION</p>
          <div class="toggle-div">
            <input type="checkbox" class="custom-control-input" id="switch-morning" <%= 'checked' if current_user.setting.morning_notification_active %>>
            <label class="custom-control-label" for="switch-morning"></label>
            <div hidden id='morning-notification-active'><%= current_user.setting.morning_notification_active %></div>
          </div>
        </div>


        <div class="custom-control custom-switch card-blink toggle-button-container text-center">
          <p class="notification-title">NIGHT NOTIFICATION</p>
          <div class="toggle-div">
            <input type="checkbox" class="custom-control-input" id="switch-night" <%= 'checked' if current_user.setting.night_notification_active %>>
            <label class="custom-control-label" for="switch-night"></label>
            <div hidden id='night-notification-active'><%= current_user.setting.night_notification_active %></div>
          </div>
        </div>


        <div class="custom-control custom-switch card-blink toggle-button-container text-center">
          <p class="notification-title">CURRENT CITY</p>
          <div class="text-center">
            <input type="" id="city-input" class="update" value="<%= current_user.city %>"/>
          </div>
        </div>

      </div>


    </div>

  </div>

</div>


<%= javascript_include_tag 'dashboard_on_desktop' %>

<%= javascript_pack_tag 'dashboard_on_desktop' %>

app/views/pages/desktop_home.html.erb
<div class="background" style="background-image: url(<%= image_url 'backgrounds/desktopback.svg' %>)">

  <div class="desktop_header_links">

    <div class="title-underlined mr-4">
      <%= link_to "SIGN UP", new_user_registration_path, class: "title" %>
    </div>

    <div class="title-underlined">
      <%= link_to "LOGIN", new_user_session_path, class: "title" %>
    </div>

  </div>

  <div class="blink_header_desktop">
    <h1>BLINK <%= image_tag("logo-blink.svg", height:"33.6", width:"102.19", alt:"vector") %></h1>
  </div>

  <div class="motto_desktop">
    <h2>Show your eyes <br> some love</h2>
  </div>



  <div class="desktop_landing_grid">

    <div class="desktop-card">
      <div class="text-center">
       <%= image_tag("vectors/landingvector1.svg", height:"231", width:"146", alt:"vector") %>
      </div>

      <p>We spend a lot of time on screens. Unfortunately, the more time we spend looking at devices,
      the more susceptible we are to dry eyes. Screens reduce the amount we blink from an average of
      15 times a minute to around five.</p>
    </div>

    <div class="desktop-card">
      <div class="text-center">
        <%= image_tag("vectors/landingvector2.svg", height:"231", width:"146", alt:"vector") %>
      </div>

      <p>There are ways to combat dry eye symptoms. Research recommends taking a one minute break from looking at screens every 20 minutes.
      That’s why BLINK will send you a desktop notification letting you know it’s time to give your eyes a rest.</p>
    </div>

    <div class="desktop-card">
      <div class="text-center">
        <%= image_tag("vectors/landingvector3.svg", height:"231", width:"146", alt:"vector") %>
      </div>

      <p class="mb-5">There are ways to retrain your brain to blink more often.
      This is why BLINK keeps track of daily recommended blinking exercises to
      improve both eye health and habits. The tools to feel better are at your fingertips!</p>

    </div>
  </div>

  <div class="d-flex justify-content-center mb-5">
    <%= link_to "SIGN UP", new_user_registration_path, class:"desk-button button btn btn-outline-success mb-3" %>
  </div>

</div>

app/views/pages/desktop_signup.html.erb
<div class="background" style="background-image: url(<%= image_url 'backgrounds/desktopback.svg' %>)">

  <div class="desktop_header_links">

    <div class="title-underlined">
      <%= link_to "LOGIN", new_user_session_path, class: "title" %>
    </div>

  </div>

  <div class="blink_header_desktop">
    <h1> <%= link_to root_path, class: "no-decoration" do %> BLINK <% end %><%= image_tag("logo-blink.svg", height:"33.6", width:"102.19", alt:"vector") %></h1>
  </div>

  <div class="motto_desktop">
    <h2>Show your eyes <br> some love</h2>
  </div>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs container" id="SignupFormDesktop">
    <%= f.input :first_name,
            label: false,
            required: true,
            placeholder: 'FIRST NAME' %>
    <%= f.input :city,
                input_html: { id:"city-input", placeholder: 'CITY' },
                label: false,
                required: true %>
    <%= f.input :email,
                label: false,
                required: true,
                input_html: { autocomplete: "email", placeholder: 'EMAIL' } %>
    <%= f.input :password,
                label: false,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password", placeholder: 'PASSWORD' } %>
    <%= f.input :password_confirmation,
                label: false,
                required: true,
                input_html: { autocomplete: "new-password", placeholder: "CONFIRM PASSWORD" } %>
  </div>
    <br><br>
<div class="text-center">
  <div class="form-actions desk-button button btn btn-outline-success mb-5 text-center">
    <%= f.button :submit, "SIGN UP", class: "orange-text" %>
  </div>
</div>
<% end %>

app/views/pages/mobile_home.html.erb
<div class="background background-mobile" style="background-image: url(<%= image_url 'backgrounds/navbarpagesbacks.svg' %>)">
  <div class="landing_header_mobile container">
    <div class="header_links">
      <div class="title-underlined">
        <%= link_to "SIGN UP", new_user_registration_path, class: "title" %>
      </div>
      <div class="title-underlined">
        <%= link_to "LOGIN", new_user_session_path, class: "title" %>
      </div>
    </div>
      <div class="text-center">
        <h1>BLINK <%= image_tag("logo-blink.svg", height:"63.6", width:"32", alt:"vector") %></h1>
        <br><br>
        <h3>Show your eyes <br> some love</h3>
      </div>
  </div>

<div class="landing_body text-center">
  <div class="mb-5 text-center container">
    <div class="viewheight">

     <%= image_tag("vectors/landingvector1.svg", height:"231", width:"146", alt:"vector") %>

        <p>We spend a lot of time on screens. Unfortunately, the more time we spend looking at devices,
        the more susceptible we are to dry eyes. Screens reduce the amount we blink from an average of
        15 times a minute to around five.</p>

    </div>

      <div class="viewheight">

        <%= image_tag("vectors/landingvector2.svg", height:"231", width:"146", alt:"vector") %>


        <p>There are ways to combat dry eye symptoms. Research recommends taking a one minute break from looking at screens every 20 minutes.
        That’s why BLINK will send you a desktop notification letting you know it’s time to give your eyes a rest.</p>

      </div>

      <div class="viewheight">
        <%= image_tag("vectors/landingvector3.svg", height:"231", width:"146", alt:"vector") %>

        <p class="mb-5">There are ways to retrain your brain to blink more often. This is why BLINK keeps track of daily recommended blinking exercises to improve both eye health and habits. The tools to feel better are at your fingertips!</p>
      </div>

      <div class="container" style="padding-top: 90px">

        <%= link_to "SIGN UP", new_user_registration_path, class:"button btn btn-outline-success mb-3" %>

        <div>
          <%= link_to "Log in", new_user_session_path %>
        </div>

      </div>
    <% if current_user %>
      <% link_to 'Take me to my dashboard', dashboard_path %>
    <% end %>
  </div>
</div>

app/views/pages/mobile_signup.html.erb
<div class="background background-mobile" style="background-image: url(<%= image_url 'backgrounds/mobile-form-background.svg' %>)">
  <div class="container">

  <div class="banner-mobile">
    <%= link_to root_path, class: "blink-header no-decoration" do %>
        <h1 class="blink-name mb-0 no-decoration">BLINK</h1>
        <%= image_tag (image_url('logo-blink.svg')), class:"blink-logo no-decoration" %>
    <% end %>
  </div>

  <div class="mobile-sign-out">
    <div class="title-underlined">
      <%= link_to "LOGIN", new_user_session_path, class: "title link-in-mobile-banner" %>
    </div>
  </div>

  <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs container" id="SignupFormMobile">
      <%= f.input :first_name,
              label: false,
              required: true,
              placeholder: 'FIRST NAME' %>
      <%= f.input :city,
                  input_html: { id:"city-input", placeholder: 'CITY' },
                  label: false,
                  required: true %>
      <%= f.input :email,
                  label: false,
                  required: true,
                  input_html: { autocomplete: "email", placeholder: 'EMAIL' } %>
      <%= f.input :password,
                  label: false,
                  required: true,
                  hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                  input_html: { autocomplete: "new-password", placeholder: 'PASSWORD' } %>
      <%= f.input :password_confirmation,
                  label: false,
                  required: true,
                  input_html: { autocomplete: "new-password", placeholder: "CONFIRM PASSWORD" } %>
    </div>

  <div class="text-center">
    <div class="form-actions desk-button button btn btn-outline-success text-center" id="signup-mobile">
      <%= f.button :submit, "SIGN UP", class: "orange-text" %>
    </div>
  </div>
  <% end %>
</div>